[package]
name = "weld-client"
version.workspace = true
edition.workspace = true
publish.workspace = true

[features]
serde = ["dep:serde", "cursor-icon/serde"]
test-support = []

[dependencies]
weld-diagnostics = { path = "../weld-diagnostics" }
cursor-icon.workspace = true
serde = { workspace = true, optional = true }
