[package]
name = "weld-hoist-local"
version.workspace = true
edition.workspace = true
publish.workspace = true

[features]
encoded-vaapi = ["weld-hoist-encoded/vaapi"]

[dependencies]
anyhow.workspace = true
calloop.workspace = true
postcard.workspace = true
rustix.workspace = true
serde.workspace = true
tracing.workspace = true
smithay = { workspace = true, features = ["wayland_frontend"] }
weld-client = { path = "../weld-client", features = ["serde"] }
weld-core = { path = "../weld-core" }
weld-hoist-core = { path = "../weld-hoist-core" }
weld-hoist-encoded = { path = "../weld-hoist-encoded", features = ["native"] }
weld-hoist-protocol = { path = "../weld-hoist-protocol" }
weld-media = { path = "../weld-media", features = ["serde"] }
