[package]
name = "weld-window-ui"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
bevy.workspace = true
tracing.workspace = true
weld-app = { path = "../weld-app" }
weld-window = { path = "../weld-window" }

[dev-dependencies]
weld-app = { path = "../weld-app", features = ["test-support"] }
