[package]
name = "weld-sway-config"
version.workspace = true
edition.workspace = true
publish.workspace = true

[features]
evaluate = ["dep:anyhow"]
input = ["evaluate", "dep:weld-input"]
output = ["evaluate", "dep:weld-output"]

[dependencies]
winnow.workspace = true
anyhow = { workspace = true, optional = true }
weld-input = { path = "../weld-input", features = ["bevy"], optional = true }
weld-output = { path = "../weld-output", optional = true }

[dev-dependencies]
insta.workspace = true
