[package]
name = "weld-i3-quirks"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
weld-float = { path = "../weld-float" }
anyhow.workspace = true
pango = { version = "=0.22.9", features = ["v1_56"] }
bevy.workspace = true
regex.workspace = true
weld-app = { path = "../weld-app" }
weld-input = { path = "../weld-input", features = ["bevy"] }
weld-sway-config = { path = "../weld-sway-config", features = ["input", "output"] }
weld-output = { path = "../weld-output" }
weld-tile = { path = "../weld-tile" }
weld-window = { path = "../weld-window" }
weld-ssd = { path = "../weld-ssd" }

[dev-dependencies]
weld-window-ui = { path = "../weld-window-ui" }
weld-client = { path = "../weld-client" }
indoc.workspace = true
weld-app = { path = "../weld-app", features = ["test-support"] }
