[package]
name = "weld-hoist-encoded"
version.workspace = true
edition.workspace = true
publish.workspace = true

[features]
native = ["dep:weld-core"]
vaapi = ["native", "dep:weld-media-vaapi", "dep:rustix"]

[dependencies]
anyhow.workspace = true
rustix = { workspace = true, optional = true }
tracing.workspace = true
weld-client = { path = "../weld-client" }
weld-core = { path = "../weld-core", optional = true }
weld-hoist-core = { path = "../weld-hoist-core" }
weld-hoist-protocol = { path = "../weld-hoist-protocol" }
weld-media = { path = "../weld-media" }
weld-media-vaapi = { path = "../weld-media-vaapi", optional = true }
